<?php

putenv('DISPLAY_ERRORS_DETAILS=' , false);

putenv('GERENCIADOR_LOJAS_MYSQL_HOST=');
putenv('GERENCIADOR_LOJAS_MYSQL_DBNAME=');
putenv('GERENCIADOR_LOJAS_MYSQL_USER=');
putenv('GERENCIADOR_LOJAS_MYSQL_PASSWORD=');
putenv('GERENCIADOR_LOJAS_MYSQL_PORT=');